"""Nox automation file."""

from nox import Session, session

python_versions = ["3.9"]


@session(python=["3.9"])
def export_ts(session: Session) -> None:
    """Export JSON schema as Pydantic classes."""
    session.install("datamodel-code-generator")

    session.run(
        "python3",
        "preprocessjson.py",
        "--input",
        "./autogenerated/schemas/wic.json",
        "--output",
        "./autogenerated/schemas/wicnonull.json"
    )
    session.run(
        "datamodel-codegen",
        "--input",
        "./autogenerated/schemas/wicnonull.json",
        "--output",
        "./autogenerated/schemas/wicschema.py",
        "--field-constraints"
    )
